# Generated by Django 4.2 on 2023-05-08 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("s_admin", "0001_initial"),
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "education_name",
                    models.CharField(max_length=50, verbose_name="education_name"),
                ),
                (
                    "education_description",
                    models.TextField(verbose_name="education_desciprtion"),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_on"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated_on"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("INACTIVE", "INACTIVE"),
                            ("PENDING", "PENDING"),
                            ("DELETED", "DELETED"),
                        ],
                        default="ACTIVE",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Educations",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="first_name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="last_name"),
                ),
                (
                    "member_code",
                    models.CharField(max_length=50, verbose_name="member_code"),
                ),
                (
                    "date_of_birth",
                    models.DateField(max_length=8, verbose_name="date_of_birth"),
                ),
                ("age", models.IntegerField(max_length=3, verbose_name="age")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "MALE"), ("F", "FEMALE"), ("O", "OTHERS")],
                        verbose_name="gender",
                    ),
                ),
                (
                    "is_old_member",
                    models.BooleanField(default=False, verbose_name="is_old_member"),
                ),
                (
                    "shg_name",
                    models.CharField(
                        default="NA", max_length=50, null=True, verbose_name="shg_name"
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("MARRIED", "MARRIED"),
                            ("SINGLE", "SINGLE"),
                            ("DIVORCED", "DIVORCED"),
                            ("WIDOWED", "WINDOWED"),
                        ],
                        max_length=15,
                        verbose_name="marital_status",
                    ),
                ),
                (
                    "father_name",
                    models.CharField(max_length=50, verbose_name="father_name"),
                ),
                (
                    "mother_name",
                    models.CharField(max_length=50, verbose_name="mother_name"),
                ),
                ("religion", models.CharField(max_length=20, verbose_name="religion")),
                (
                    "community",
                    models.CharField(
                        choices=[
                            ("SC", "SC"),
                            ("ST", "ST"),
                            ("MBC", "MBC"),
                            ("BC", "BC"),
                            ("OC", "OC"),
                        ],
                        max_length=3,
                        verbose_name="community",
                    ),
                ),
                (
                    "disability",
                    models.BooleanField(default=False, verbose_name="disabled"),
                ),
                (
                    "mobile_number",
                    models.CharField(max_length=11, verbose_name="mobile_number"),
                ),
                (
                    "email",
                    models.EmailField(max_length=50, null=True, verbose_name="email"),
                ),
                (
                    "joined_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="joined_on"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("INACTIVE", "INACTIVE"),
                            ("PENDING", "PENDING"),
                            ("DELETED", "DELETED"),
                        ],
                        default="ACTIVE",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="s_members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
            },
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occupation_name",
                    models.CharField(max_length=50, verbose_name="occupation_name"),
                ),
                (
                    "occupation_description",
                    models.TextField(verbose_name="occupation_description"),
                ),
                (
                    "occupation_type",
                    models.CharField(max_length=50, verbose_name="occupation_type"),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_on"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated_on"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("INACTIVE", "INACTIVE"),
                            ("PENDING", "PENDING"),
                            ("DELETED", "DELETED"),
                        ],
                        default="ACTIVE",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Occupation",
                "verbose_name_plural": "Occupations",
            },
        ),
        migrations.CreateModel(
            name="MemberRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(max_length=50, verbose_name="txn_number"),
                ),
                (
                    "payment_mode",
                    models.CharField(max_length=50, verbose_name="payment_mode"),
                ),
                (
                    "payment_through",
                    models.CharField(max_length=50, verbose_name="payment_through"),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s_members.member",
                        verbose_name="",
                    ),
                ),
                (
                    "registration_fee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s_admin.feesettings",
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "MemberRegistration",
                "verbose_name_plural": "MemberRegistrations",
            },
        ),
        migrations.CreateModel(
            name="MemberOccupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s_members.member",
                    ),
                ),
                (
                    "occupation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s_members.occupation",
                    ),
                ),
            ],
            options={
                "verbose_name": "MemberOccupation",
                "verbose_name_plural": "MemberOccupations",
            },
        ),
        migrations.CreateModel(
            name="MemberEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=True, verbose_name="is_completed"),
                ),
                (
                    "completed_year",
                    models.IntegerField(
                        max_length=4, null=True, verbose_name="course_completed_year"
                    ),
                ),
                (
                    "education_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s_members.education",
                        verbose_name="education_id",
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s_members.member",
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "MemberEducation",
                "verbose_name_plural": "MemberEducations",
            },
        ),
        migrations.CreateModel(
            name="MemberAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_ln_one",
                    models.CharField(max_length=50, verbose_name="address_line_one"),
                ),
                (
                    "address_ln_two",
                    models.CharField(max_length=50, verbose_name="address_line_two"),
                ),
                (
                    "address_ln_three",
                    models.CharField(
                        max_length=50, null=True, verbose_name="address_line_three"
                    ),
                ),
                ("district", models.CharField(max_length=50, verbose_name="district")),
                (
                    "state",
                    models.CharField(
                        default="Tamil Nadu", max_length=50, verbose_name="state"
                    ),
                ),
                (
                    "taluk",
                    models.CharField(max_length=50, null=True, verbose_name="taluk"),
                ),
                (
                    "local_body",
                    models.CharField(
                        max_length=50, null=True, verbose_name="local_body"
                    ),
                ),
                ("pincode", models.IntegerField(max_length=6, verbose_name="pincode")),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities_light.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities_light.country",
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s_members.member",
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "MemberAddress",
                "verbose_name_plural": "MemberAddresss",
            },
        ),
    ]
