# Generated by Django 4.2 on 2023-05-27 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("s_members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created_by",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="memberaddress",
            name="member_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="s_members.member",
                verbose_name="member",
            ),
        ),
        migrations.AlterField(
            model_name="memberregistration",
            name="member_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="s_members.member",
                verbose_name="member",
            ),
        ),
    ]
