# Generated by Django 4.2 on 2023-05-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s_members", "0003_alter_member_member_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PAID", "PAID"),
                    ("UNPAID", "UNPAID"),
                    ("ON-HOLD", "ON-HOLD"),
                ],
                default="UNPAID",
                verbose_name="Payment Status",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="registration_fees",
            field=models.FloatField(default=500.0, verbose_name="Registration Fees"),
        ),
        migrations.AddField(
            model_name="memberregistration",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PAID", "PAID"),
                    ("UNPAID", "UNPAID"),
                    ("ON-HOLD", "ON-HOLD"),
                ],
                default="UNPAID",
                verbose_name="Payment Status",
            ),
        ),
    ]
