# Generated by Django 4.2 on 2023-05-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s_members", "0005_alter_memberregistration_registration_fee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberregistration",
            name="payment_mode",
            field=models.CharField(
                choices=[("ONLINE", "ONLINE"), ("OFFLINE", "OFFLINE")],
                default="ONLINE",
                verbose_name="payment_mode",
            ),
        ),
    ]
