# Generated by Django 4.2 on 2023-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s_members", "0006_alter_memberregistration_payment_mode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memberaddress",
            options={
                "verbose_name": "Member Address",
                "verbose_name_plural": "Member Addresss",
            },
        ),
        migrations.AlterModelOptions(
            name="membereducation",
            options={
                "verbose_name": "Member Education",
                "verbose_name_plural": "Member Educations",
            },
        ),
        migrations.AlterModelOptions(
            name="memberoccupation",
            options={
                "verbose_name": "Member Occupation",
                "verbose_name_plural": "Member Occupations",
            },
        ),
        migrations.AlterModelOptions(
            name="memberregistration",
            options={
                "verbose_name": "Member Registration Status",
                "verbose_name_plural": "Member Registrations status",
            },
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(
                max_length=50, null=True, unique=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="mobile_number",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="mobile_number"
            ),
        ),
    ]
