# Generated by Django 4.2 on 2023-05-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s_admin", "0002_permissionsettings_alter_streets_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rolepermissions",
            name="permission_id",
        ),
        migrations.AddField(
            model_name="rolepermissions",
            name="permission_id",
            field=models.ManyToManyField(
                to="s_admin.permissionsettings", verbose_name="Permission id"
            ),
        ),
    ]
