# Generated by Django 4.2 on 2023-05-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s_admin", "0004_alter_feesettings_fee_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feesettings",
            name="fee_type",
            field=models.CharField(verbose_name="Fee Mode"),
        ),
    ]
