# Generated by Django 4.2 on 2023-05-29 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("s_members", "0003_alter_member_member_code"),
        ("s_group", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupmembers",
            name="member_id",
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_members",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s_group.groupmembers",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s_members.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="groupmembers",
            name="member_id",
            field=models.ManyToManyField(to="s_members.member", verbose_name="Member"),
        ),
    ]
